export const departments = [
  {
    id: "dci",
    name: "Department of Commerce and Industries",
    short: "Industries",
    color: "#1d6f6b",
    records: 12840,
  },
  {
    id: "gst",
    name: "Commercial Taxes / GST",
    short: "GST",
    color: "#b15b18",
    records: 18320,
  },
  {
    id: "labour",
    name: "Labour Department",
    short: "Labour",
    color: "#5f5ab8",
    records: 9050,
  },
  {
    id: "pcb",
    name: "Pollution Control Board",
    short: "KSPCB",
    color: "#2f7d32",
    records: 6210,
  },
  {
    id: "bescom",
    name: "Utility Consumption Streams",
    short: "Utilities",
    color: "#9a3d47",
    records: 22450,
  },
  {
    id: "bbmp",
    name: "Municipal Trade Licenses",
    short: "ULB",
    color: "#34689a",
    records: 11480,
  },
];

export const sourceRecords = [
  {
    id: "rec-1001",
    departmentId: "dci",
    name: "Bengaluru Precision Components Pvt Ltd",
    address: "Plot 14, Peenya Industrial Area Phase 2, Bengaluru",
    pin: "560058",
    pan: "AAECB4321K",
    gstin: "29AAECB4321K1Z5",
    owner: "Arvind Rao",
    district: "Bengaluru Urban",
    lastUpdated: "2026-04-12",
    employees: 145,
  },
  {
    id: "rec-1002",
    departmentId: "gst",
    name: "Bangalore Precision Comp. Private Limited",
    address: "No 14 Peenya Indl Area Ph II, Bangalore",
    pin: "560058",
    pan: "AAECB4321K",
    gstin: "29AAECB4321K1Z5",
    owner: "A Rao",
    district: "Bengaluru Urban",
    lastUpdated: "2026-04-19",
    employees: 141,
  },
  {
    id: "rec-1003",
    departmentId: "labour",
    name: "BPC Components Pvt. Ltd.",
    address: "Peenya Industrial Area, Phase 2, Bengaluru",
    pin: "560058",
    pan: "AAECB4321K",
    gstin: "",
    owner: "Aravind Rao",
    district: "Bengaluru Urban",
    lastUpdated: "2026-03-27",
    employees: 148,
  },
  {
    id: "rec-1010",
    departmentId: "dci",
    name: "Nandi Textile Works Unit 2",
    address: "KIADB Industrial Area, Sira Road, Tumakuru",
    pin: "572104",
    pan: "AAFNW9088R",
    gstin: "",
    owner: "Meera Hegde",
    district: "Tumakuru",
    lastUpdated: "2025-11-18",
    employees: 76,
  },
  {
    id: "rec-1011",
    departmentId: "gst",
    name: "Nandi Textiles U-2",
    address: "Sira Rd KIADB Area, Tumkur",
    pin: "572106",
    pan: "AAFNW9088R",
    gstin: "29AAFNW9088R1Z2",
    owner: "M Hegde",
    district: "Tumakuru",
    lastUpdated: "2026-01-21",
    employees: 74,
  },
  {
    id: "rec-1020",
    departmentId: "pcb",
    name: "Mysuru Agro Foods LLP",
    address: "Hebbal Industrial Estate, Mysuru",
    pin: "570018",
    pan: "ABBFM1201Q",
    gstin: "29ABBFM1201Q1Z8",
    owner: "Kiran Dev",
    district: "Mysuru",
    lastUpdated: "2026-02-02",
    employees: 52,
  },
  {
    id: "rec-1021",
    departmentId: "bescom",
    name: "Mysore Agro Food Logistics",
    address: "Hebbal Ind Estate, Mysore",
    pin: "570018",
    pan: "",
    gstin: "",
    owner: "K Dev",
    district: "Mysuru",
    lastUpdated: "2026-04-15",
    employees: 51,
  },
  {
    id: "rec-1030",
    departmentId: "dci",
    name: "Malnad Coffee Curing Company",
    address: "Belur Road, Chikkamagaluru",
    pin: "577101",
    pan: "AABCM9944L",
    gstin: "29AABCM9944L1Z3",
    owner: "Prakash Menon",
    district: "Chikkamagaluru",
    lastUpdated: "2023-06-14",
    employees: 28,
  },
  {
    id: "rec-1031",
    departmentId: "gst",
    name: "Malnad Coffee Traders",
    address: "Belur Main Road, Chikmagalur",
    pin: "577102",
    pan: "AAGFM3388T",
    gstin: "29AAGFM3388T1ZD",
    owner: "P Menon",
    district: "Chikkamagaluru",
    lastUpdated: "2024-02-10",
    employees: 12,
  },
  {
    id: "rec-1040",
    departmentId: "labour",
    name: "Hubballi Green Circuits Pvt Ltd",
    address: "Gokul Road Industrial Estate, Hubballi",
    pin: "580030",
    pan: "AAECH7440D",
    gstin: "",
    owner: "Sonal Patil",
    district: "Dharwad",
    lastUpdated: "2025-12-01",
    employees: 118,
  },
  {
    id: "rec-1041",
    departmentId: "pcb",
    name: "Hubli Green Circuit Private Ltd",
    address: "Gokul Industrial Estate, Hubli",
    pin: "580030",
    pan: "",
    gstin: "29AAECH7440D1Z9",
    owner: "S Patil",
    district: "Dharwad",
    lastUpdated: "2026-01-03",
    employees: 116,
  },
  {
    id: "rec-1050",
    departmentId: "bbmp",
    name: "Coastal Marine Logistics",
    address: "Baikampady Industrial Area, Mangaluru",
    pin: "575011",
    pan: "AAGCC2026M",
    gstin: "29AAGCC2026M1Z4",
    owner: "Rahul Shetty",
    district: "Dakshina Kannada",
    lastUpdated: "2026-04-05",
    employees: 64,
  },
];

export const candidateMatches = [
  {
    id: "match-001",
    recordA: "rec-1001",
    recordB: "rec-1002",
    confidence: 98,
    band: "High",
    defaultDecision: "auto-linked",
    ubid: "UBID-KA-2026-0001",
    signals: {
      identifier: 100,
      name: 87,
      address: 92,
      geography: 100,
      owner: 74,
    },
    explanation:
      "Matched on exact GSTIN and PAN, same PIN code, highly similar address, and consistent owner initials.",
  },
  {
    id: "match-002",
    recordA: "rec-1001",
    recordB: "rec-1003",
    confidence: 91,
    band: "High",
    defaultDecision: "auto-linked",
    ubid: "UBID-KA-2026-0001",
    signals: {
      identifier: 96,
      name: 78,
      address: 90,
      geography: 100,
      owner: 83,
    },
    explanation:
      "Matched on PAN, same PIN code, strong address overlap, and owner-name consistency despite abbreviated business name.",
  },
  {
    id: "match-003",
    recordA: "rec-1010",
    recordB: "rec-1011",
    confidence: 76,
    band: "Medium",
    defaultDecision: "review",
    ubid: "",
    signals: {
      identifier: 92,
      name: 81,
      address: 68,
      geography: 70,
      owner: 73,
    },
    explanation:
      "PAN matches and names are consistent, but PIN code differs and address needs reviewer confirmation.",
  },
  {
    id: "match-004",
    recordA: "rec-1020",
    recordB: "rec-1021",
    confidence: 72,
    band: "Medium",
    defaultDecision: "review",
    ubid: "",
    signals: {
      identifier: 18,
      name: 73,
      address: 88,
      geography: 100,
      owner: 72,
    },
    explanation:
      "Same industrial estate and owner initials, but utility stream lacks PAN/GSTIN and name includes an extra logistics token.",
  },
  {
    id: "match-005",
    recordA: "rec-1030",
    recordB: "rec-1031",
    confidence: 49,
    band: "Low",
    defaultDecision: "separate",
    ubid: "",
    signals: {
      identifier: 0,
      name: 58,
      address: 71,
      geography: 84,
      owner: 41,
    },
    explanation:
      "Similar locality and partial name overlap, but PAN/GSTIN disagree and business names imply different entities.",
  },
  {
    id: "match-006",
    recordA: "rec-1040",
    recordB: "rec-1041",
    confidence: 79,
    band: "Medium",
    defaultDecision: "review",
    ubid: "",
    signals: {
      identifier: 82,
      name: 86,
      address: 85,
      geography: 100,
      owner: 68,
    },
    explanation:
      "GSTIN contains matching PAN pattern and address is strong, but one source does not provide the identifier directly.",
  },
];

export const businesses = [
  {
    id: "biz-001",
    ubid: "UBID-KA-2026-0001",
    name: "Bengaluru Precision Components Pvt Ltd",
    status: "Active",
    district: "Bengaluru Urban",
    confidence: 98,
    linkedRecords: ["rec-1001", "rec-1002", "rec-1003"],
    reason:
      "Recent GST filing, labour return, inspection update, and steady power consumption within the last 45 days.",
    lastActivity: "2026-04-20",
    departments: ["dci", "gst", "labour", "bescom"],
  },
  {
    id: "biz-002",
    ubid: "UBID-KA-2026-0002",
    name: "Nandi Textile Works Unit 2",
    status: "Dormant",
    district: "Tumakuru",
    confidence: 76,
    linkedRecords: ["rec-1010"],
    reason:
      "Historically active unit with no inspection, filing, or utility signal after January 2026.",
    lastActivity: "2026-01-21",
    departments: ["dci", "gst"],
  },
  {
    id: "biz-003",
    ubid: "UBID-KA-2026-0003",
    name: "Mysuru Agro Foods LLP",
    status: "Active",
    district: "Mysuru",
    confidence: 72,
    linkedRecords: ["rec-1020"],
    reason:
      "Pollution consent renewal and utility consumption were observed inside the active time window.",
    lastActivity: "2026-04-15",
    departments: ["pcb", "bescom"],
  },
  {
    id: "biz-004",
    ubid: "UBID-KA-2026-0004",
    name: "Malnad Coffee Curing Company",
    status: "Closed",
    district: "Chikkamagaluru",
    confidence: 94,
    linkedRecords: ["rec-1030"],
    reason:
      "No filing or inspection for more than 30 months and cancellation notice recorded by source department.",
    lastActivity: "2023-06-14",
    departments: ["dci", "gst"],
  },
  {
    id: "biz-005",
    ubid: "UBID-KA-2026-0005",
    name: "Hubballi Green Circuits Pvt Ltd",
    status: "Dormant",
    district: "Dharwad",
    confidence: 79,
    linkedRecords: ["rec-1040"],
    reason:
      "Recent compliance history exists, but production and inspection signals are absent in the current window.",
    lastActivity: "2026-01-03",
    departments: ["labour", "pcb"],
  },
  {
    id: "biz-006",
    ubid: "UBID-KA-2026-0006",
    name: "Coastal Marine Logistics",
    status: "Active",
    district: "Dakshina Kannada",
    confidence: 96,
    linkedRecords: ["rec-1050"],
    reason:
      "Municipal renewal, GST return, and warehouse inspection are all recent and mutually consistent.",
    lastActivity: "2026-04-05",
    departments: ["bbmp", "gst", "dci"],
  },
];

export const activityEvents = [
  {
    id: "evt-001",
    ubid: "UBID-KA-2026-0001",
    date: "2026-04-20",
    departmentId: "gst",
    type: "GST filing",
    strength: "Strong",
    detail: "GSTR-3B filed for March 2026.",
  },
  {
    id: "evt-002",
    ubid: "UBID-KA-2026-0001",
    date: "2026-04-18",
    departmentId: "bescom",
    type: "Utility signal",
    strength: "Strong",
    detail: "Power consumption remains inside active manufacturing band.",
  },
  {
    id: "evt-003",
    ubid: "UBID-KA-2026-0001",
    date: "2026-03-27",
    departmentId: "labour",
    type: "Labour return",
    strength: "Medium",
    detail: "Employee count update submitted.",
  },
  {
    id: "evt-004",
    ubid: "UBID-KA-2026-0002",
    date: "2026-01-21",
    departmentId: "gst",
    type: "GST filing",
    strength: "Medium",
    detail: "Last tax filing observed in January 2026.",
  },
  {
    id: "evt-005",
    ubid: "UBID-KA-2026-0003",
    date: "2026-04-15",
    departmentId: "bescom",
    type: "Utility signal",
    strength: "Strong",
    detail: "Cold-chain unit consumption trend is active.",
  },
  {
    id: "evt-006",
    ubid: "UBID-KA-2026-0003",
    date: "2026-02-02",
    departmentId: "pcb",
    type: "Consent renewal",
    strength: "Strong",
    detail: "Consent renewal accepted by board.",
  },
  {
    id: "evt-007",
    ubid: "UBID-KA-2026-0004",
    date: "2023-06-14",
    departmentId: "dci",
    type: "Cancellation notice",
    strength: "Strong",
    detail: "Industrial registration marked for closure verification.",
  },
  {
    id: "evt-008",
    ubid: "UBID-KA-2026-0005",
    date: "2026-01-03",
    departmentId: "pcb",
    type: "Inspection",
    strength: "Weak",
    detail: "Desk inspection request raised; no production evidence since.",
  },
  {
    id: "evt-009",
    ubid: "UBID-KA-2026-0006",
    date: "2026-04-05",
    departmentId: "bbmp",
    type: "Trade renewal",
    strength: "Strong",
    detail: "Warehouse license renewed for FY 2026.",
  },
];

export const unmatchedEvents = [
  {
    id: "evt-u01",
    sourceName: "Nandi Textiles Unit II",
    departmentId: "bescom",
    date: "2026-03-18",
    type: "Utility signal",
    detail: "Meter activity exists but address differs from current UBID cluster.",
    suggestedMatch: "match-003",
  },
  {
    id: "evt-u02",
    sourceName: "Sri Lakshmi Foods",
    departmentId: "gst",
    date: "2026-04-03",
    type: "GST filing",
    detail: "Identifier missing in master data; queued for source-system reconciliation.",
    suggestedMatch: "",
  },
];

export const queryResults = [
  {
    id: "q1",
    title: "Active in GST, missing in Industries",
    question: "Find operating businesses that are visible in tax filings but absent from industry master data.",
    insight: "2 high-priority outreach candidates",
    rows: [
      ["Mysuru Agro Foods LLP", "Mysuru", "GST + Utilities", "Create DCI verification task"],
      ["Sri Lakshmi Foods", "Bengaluru Urban", "GST only", "Resolve unmatched event"],
    ],
  },
  {
    id: "q2",
    title: "Dormant with high employment",
    question: "Find historically active units with high employee counts and no recent operations signal.",
    insight: "2 units require field validation",
    rows: [
      ["Hubballi Green Circuits Pvt Ltd", "Dharwad", "118 workers", "Dormant"],
      ["Nandi Textile Works Unit 2", "Tumakuru", "76 workers", "Dormant"],
    ],
  },
  {
    id: "q3",
    title: "Wrong-merge risk watchlist",
    question: "Surface pairs where a false positive merge would have high policy impact.",
    insight: "1 pair must stay separate",
    rows: [
      ["Malnad Coffee Curing Company", "Chikkamagaluru", "PAN/GSTIN conflict", "Keep separate"],
      ["Malnad Coffee Traders", "Chikkamagaluru", "Shared locality only", "Keep separate"],
    ],
  },
];

export const architectureNodes = [
  {
    title: "Ingest",
    copy: "Pull department masters and event streams without modifying source systems.",
  },
  {
    title: "Standardise",
    copy: "Normalize names, addresses, identifiers, districts, PIN codes, and owner signals.",
  },
  {
    title: "Resolve",
    copy: "Score multi-signal candidate links and generate defendable UBID clusters.",
  },
  {
    title: "Review",
    copy: "Route medium-confidence cases to reviewers with exact evidence and reversibility.",
  },
  {
    title: "Classify",
    copy: "Map events to UBIDs and assign Active, Dormant, or Closed with reasons.",
  },
  {
    title: "Query",
    copy: "Expose policy-ready answers, audit trails, and unmatched event queues.",
  },
];

export const districtSignals = [
  { district: "Bengaluru Urban", active: 1240, dormant: 188, closed: 64 },
  { district: "Mysuru", active: 542, dormant: 91, closed: 26 },
  { district: "Tumakuru", active: 438, dormant: 116, closed: 33 },
  { district: "Dharwad", active: 392, dormant: 104, closed: 41 },
  { district: "Dakshina Kannada", active: 318, dormant: 64, closed: 18 },
  { district: "Chikkamagaluru", active: 156, dormant: 72, closed: 47 },
];
